# ======================================= Learning configs ==================================
n_epoch: 15
batch_size: 16
test_batch_size: 16
lr: 0.0004
mi_lr: 0.001
loss_weights: 0.5
clip_gradient: 0.5
start_epoch: 0
weight_decay: 5e-4

  # ======================================= Print and snapshot configs ==================================
snapshot_pref: 
    /project/ag-jafra/Souptik/CMG_New/Experiments/CMG_trial1/MOSEI_Models2/256codebook_Norm_seq10_10_unsupervised_reg_TAV_L2_test/
print_freq: 1
eval_freq: 1


