# ======================================= Learning configs ==================================
n_epoch: 60
batch_size: 32
test_batch_size: 32
lr: 0.0001
mi_lr: 0.001
loss_weights: 0.5
clip_gradient: 0.5
start_epoch: 0
weight_decay: 5e-4

  # ======================================= Print and snapshot configs ==================================
snapshot_pref: 
    /project/ag-jafra/Souptik/CMG_New/Experiments/CMG_trial1/MOSEI_Tests_1/MOSEI_128dim_256_Dynamic_Padding_reg_50_unsupervised_TAV_L2_26/CMG_text/
print_freq: 1
eval_freq: 1


