# ======================================= Learning configs ==================================
n_epoch: 30
batch_size: 16
test_batch_size: 16
lr: 0.0004
mi_lr: 0.001
loss_weights: 0.5
clip_gradient: 0.5
start_epoch: 0
weight_decay: 5e-4

  # ======================================= Print and snapshot configs ==================================
snapshot_pref: 
    /project/ag-jafra/Souptik/CMG_New/Experiments/CMG_trial1/MOSEI_Models_3/ContentAware_MOSEI_unsupervised_VAT_contrastive_30dim_NewAttention_window/
print_freq: 1
eval_freq: 1


